apiVersion: v1
kind: Secret
metadata:
  name: quasar-tracing-credentials
  namespace: {{ include "quasar-tracing.namespace" . }}
  labels:
    {{- include "quasar-tracing.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.clickhouse.credentials.user | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.credentials.password | quote }}

