apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "quasar-tracing.namespace" . }}-kafka-data
  labels:
    {{- include "quasar-tracing.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  capacity:
    storage: {{ .Values.kafka.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.kafka.storage.reclaimPolicy }}
  storageClassName: ""
  claimRef:
    namespace: {{ include "quasar-tracing.namespace" . }}
    name: data-kafka-0
  hostPath:
    path: {{ .Values.kafka.storage.hostPath | quote }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "quasar-tracing.namespace" . }}-clickhouse-data
  labels:
    {{- include "quasar-tracing.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  capacity:
    storage: {{ .Values.clickhouse.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.clickhouse.storage.reclaimPolicy }}
  storageClassName: ""
  claimRef:
    namespace: {{ include "quasar-tracing.namespace" . }}
    name: data-clickhouse-0
  hostPath:
    path: {{ .Values.clickhouse.storage.hostPath | quote }}
    type: DirectoryOrCreate

