receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  filter/drop_http_noise:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(name, "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE|CONNECT|HTTP)$")'
        - 'IsMatch(name, "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE|CONNECT|HTTP) /$")'
        - 'IsMatch(name, "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE|CONNECT|HTTP) /api/?$")'
        - 'IsMatch(name, "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE|CONNECT|HTTP) /error$")'
        - 'IsMatch(name, "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE|CONNECT|HTTP) .*[\\*].*$")'
        - 'IsMatch(name, "^(HEAD|OPTIONS|HTTP)( |$).*")'
  memory_limiter:
    limit_mib: 512
    check_interval: 5s
  batch:
    timeout: 5s
    send_batch_size: 1000

exporters:
  kafka:
    brokers:
      - kafka:9092
    traces:
      topic: otel-traces
      encoding: otlp_proto
    logs:
      topic: otel-logs
      encoding: otlp_json
    metrics:
      topic: otel-metrics
      encoding: otlp_proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop_http_noise, memory_limiter, batch]
      exporters: [kafka]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [kafka]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [kafka]
